### ISSUE TITLE
Custom coloring

### ISSUE THREAD

**Issue by HallerPatrick** [HallerPatrick/frosch#2]
Allow for custom coloring which will can be passed in the hook function. Using the color themes from pygments

**Comment by dvolgyes** [comment]
Hi,

Another thing to consider: not just coloring the values, but also the variables, based on their types.
Now integers are purple(ish), strings are yellow, etc.
So in ``` x = x + z[index] + 4 + text ```
You could make x green (None), z white and bold (array), index purple (because it is integer) , 4 purple, text yellow.

Another option: make all variables white if they have the same type, 
or make white the majority of the variables, and color the outliers (either based on color scheme,
or just make it red as a type outlier)

**Comment by HallerPatrick** [comment]
This sounds like a lot of work, for creating and implementing these colouring strategies. Currently  pygments is used, which colours everything as a whole. Which IMO is great and robust.

**Comment by HallerPatrick** [comment]
After merging the themes branch you can choose from > 20 different color themes, which should be sufficient enough for now. What also should be changeable is the color of the left line number (which is currently blue).

**Comment by dvolgyes** [comment]
Hi,

It is a lot of work.
I did not want to complain, i meant it as an inspiration.
I am not sure which direction you want to take, or how much time you want to spend on it.
So the point was: here is an idea, maybe you will like it, just you haven't thought about it. But i think the coloring is already good enough, anything else is just extra. :)

-------- Original Message --------

**Comment by HallerPatrick** [comment]
Don't get me wrong, I did not understand this as a complain :)

I see your point, you want more visual information, in terms of clearly seeing the outlier for example. 
Which is a good thing, but maybe over the top for the moment. If you can give me a pull request I will happily review it
and we will see.

But for now I will put this in the back and work on the other suggestion you gave me from the other issues ;)
